---
  - name: update cache
    sudo: true
    apt: update_cache=true

  - name: install latest nginx
    sudo: true
    apt: pkg=nginx state=present

  - name: nginx configuration
    template: src='nginx.conf.j2' dest='/etc/nginx/nginx.conf' group=root owner=root mode=0644
    sudo: true
