---
- name: "Launch AMI instance"
  ec2:
    ec2_url: "{{ aws_credentials.aws_url }}"
    aws_access_key: "{{ aws_credentials.aws_access_key_id }}"
    aws_secret_key: "{{ aws_credentials.aws_secret_access_key_id }}" 
    region: "{{ aws_credentials.aws_region }}"
    key_name: "{{ aws_credentials.key_pair }}"
    instance_type: t2.micro
    image: <ami-image>
    wait: yes
    group: <security-group>
    count: 1
    vpc_subnet_id: <vpc-subnet-id>
    assign_public_ip: yes
    instance_tags:
       Name: <instance-name>
  register: ec2

- name: "EC2 Instances created"
  debug:  
  with_items: ec2.instances
  when: item | length > 0

- name: Add new instance to host group
  add_host: hostname={{ item.public_ip }} groupname=launched
  with_items: ec2.instances

- name: Wait for SSH to come up
  local_action: wait_for host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
  with_items: ec2.instances