---
  - name: downloading ruby
    get_url: url=http://ftp.ruby-lang.org/pub/ruby/2.2/ruby-2.2.1.tar.gz dest=/tmp  

  - name: 'unarchiving ruby'  
    unarchive: src=/tmp/ruby-2.2.1.tar.gz dest=/tmp copy=no

  - name: 'configure ruby'
    command: chdir=/tmp/ruby-2.2.1 ./configure --prefix=/usr/local

  - name: 'make ruby'
    command: chdir=/tmp/ruby-2.2.1 make

  - name: 'make install ruby'
    command: chdir=/tmp/ruby-2.2.1 sudo make install